### ISSUE TITLE
בדיקת מטלה 7

### ISSUE THREAD

**Issue by michael-lemberger** [Game-Dev-Project/The-Blacksmith-Game#1]
transform.Rotate(new Vector2(0, 180));
 במקום זה:
 SpriteRenderer.flipX

**Comment by michael-lemberger** [comment]
בנוסף, הליך ההתחלה חמוד והכל, אבל אחרי שהורגים את האויבים, לא ברור אם יש המשך.
בנוסף אם יש חיים, כדאי לתת על זה משוב לשחקן

**Comment by avielc11** [comment]
טיפלנו תודה
