### ISSUE TITLE
המשחק

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Project/The-Blacksmith-Game#3]
שיחקתי במשחק שלכם, אהבתי את תהליך ההתחלה - מאד ברור מה צריך לעשות - ללכת בשביל לכיוון העיר ולהרוג את האויבים. 
גם העולם שבניתם יפה ומושקע. השאלה היא מה קורה אחר-כך?

**Comment by avielc11** [comment]
הוספנו עוד שלבים ובנינו את העלילה. יש לחימה באויבים ואסיפת המשאבים
