### ISSUE TITLE
המשחק לא מעודכן

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Project/The-Blacksmith-Game#4]
המשחק בקישור https://a-team-3.itch.io/the-black-smith לא מעודכן - הוא מלפני שבוע - ויש בו עדיין כמה באגים. אנא העלו משחק מעודכן בהקדם.

**Comment by SaltyByte** [comment]
הItch מעודכן עכשיו.

**Comment by avielc11** [comment]
טופל
