### ISSUE TITLE
אני תקוע בארמון

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Project/The-Blacksmith-Game#9]
הגעתי לארמון עם השלדים, הרגתי את כל השלדים ולא הגעתי לשום מקום. לא ברור מה צריך לעשות כאן?

**Comment by avielc11** [comment]
זה השלב האחרון לבנתיים ופיתחנו עד כאן
כרגע אנחנו עובדים על על שאר האישיוז שפתחת...
כל החיווי של המשאבים והכל נמצא אבל בגלל שהמסך חתוך אז לא רואים אותם
אנחנו כרגע מתקנים
